version: '3.7'

services:
  nginx:
    build:
      context: ./nginx
      args:
        - uid=${USER_ID}
        - gid=${GROUP_ID}
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - frontend
      - backend
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro # Pour avoir le même timezone entre le host et le container
      - /opt/volumes/nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Le fichier de conf de nginx
      - /opt/volumes/nginx/vhosts.conf:/etc/nginx/conf.d/default.conf # Le fichier des vhosts
      - /opt/volumes/nginx/global:/etc/nginx/global # Un dossier avec des confs supplémentaire
      - /opt/volumes/nginx/certs:/etc/nginx/certs # Le dossier contenant les certificats
      - /opt/volumes/logs/nginx:/var/log/nginx # Pour avoir les logs de nginx sur le host
      - /opt/volumes/www:/var/www/html # Le dossier où se trouve le(s) site(s)
      - /opt/volumes/cache:/tmp/phpcache # Le dossier de cache

  php-fpm:
    build:
      context: ./php
      args:
        - uid=${USER_ID}
        - gid=${GROUP_ID}
    container_name: php-fpm
    hostname: php-fpm
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - backend
    volumes:
      - /opt/volumes/php/php.ini:/usr/local/etc/php/php.ini:ro # Le fichier de conf php
      - /opt/volumes/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro # Le fichier de conf php-fpm
      - /opt/volumes/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro # Le fichier de conf de la pool
      - /opt/volumes/php/msmtprc:/etc/msmtprc:ro # Le fichier de conf de msmtp pour l'envoi de mail
      # - /opt/volumes/php/session:/session # Le dossier des session php
      - /opt/volumes/logs/php:/var/log # Pour avoir les logs de PHP sur le host
      - /opt/volumes/www:/var/www/html # Pour dire à PHP où se situe le site
      - /opt/volumes/cache:/tmp/phpcache # Le dossier de cache

networks:
  frontend:
    external: true
  backend:
    external: true
