version: '3.7'

services:
  mariadb:
    image: mariadb:10.5.8
    container_name: mariadb
    hostname: mariadb
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    network_mode: host
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASS}
    volumes:
      - /opt/volumes/mysql/data:/var/lib/mysql # Pour avoir les bases de données sur le host
      - /opt/volumes/mysql/conf:/etc/mysql/conf.d
      - /opt/volumes/mysql/logs:/var/log/mysql
